# Form implementation generated from reading ui file 'C:\Users\Admin\PycharmProjects\DOANCUOIKY-master\ManagerMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(382, 109)
        MainWindow.setStyleSheet("background-color: rgb(255, 252, 229);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonEmployeeManagement = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonEmployeeManagement.setGeometry(QtCore.QRect(200, 20, 171, 41))
        self.pushButtonEmployeeManagement.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonEmployeeManagement.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(240, 217, 212);")
        self.pushButtonEmployeeManagement.setObjectName("pushButtonEmployeeManagement")
        self.pushButtonMaterialManagement = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMaterialManagement.setGeometry(QtCore.QRect(10, 20, 171, 41))
        self.pushButtonMaterialManagement.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonMaterialManagement.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(205, 221, 167);")
        self.pushButtonMaterialManagement.setObjectName("pushButtonMaterialManagement")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 382, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonEmployeeManagement.setText(_translate("MainWindow", "EmployeeManagement"))
        self.pushButtonMaterialManagement.setText(_translate("MainWindow", "MaterialManagement"))
